server:
   port: 8765
   
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka

management:
   endpoints:
      web:
         exposure:
            include:
            - '*'

spring:
   application:
      name: api-gateway
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
         routes:
         - id: cliente-service
           uri: lb://cliente-service
           predicates:
           - Path=/cliente-service/**
         - id: javer-service
           uri: lb://javer-service
           predicates:
           - Path=/javer-service/**
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - url: /javer-service/docs
        name: Javer Service
      - url: /cliente-service/docs
        name: Cliente Service