server:
  port: 8080

eureka:
  client:
    service-url:
      defaultone: http://localhost:8761/eureka

  
spring:
  application:
    name: javer-service

  web:
    locale-resolver: fixed
    locale: pt_BR

feign:
  httpclient:
    hc5:
      enabled: true
#springdoc:
#  swagger-ui:
#    path: /docs-javer-service.html
#  api-docs:
#    path: /docs-javer-service
#  packagesToScan: com.eggzin.javer_service.web.controller