server:
  port: 8080

eureka:
  client:
    service-url:
      defaultone: http://localhost:8761/eureka

  
spring:
  application:
    name: javer-service

  web:
    locale-resolver: fixed
    locale: pt_BR

feign:
  httpclient:
    hc5:
      enabled: true
springdoc:
  swagger-ui:
    path: /javer-service/docs.html
  api-docs:
    path: /javer-service/docs
  packagesToScan: com.eggzin.javer_service.web.controller